site_name: Pipeline Finatec

repo_name: 'mkdocs'
# repo_url: https://github.com/Interacao-Humano-Computador/2023.1-OpenStreetMap/
# site_url: https://interacao-humano-computador.github.io/2023.1-OpenStreetMap/
# edit_uri: edit/main/page/docs/